apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cos-fleetshard-connectors
  labels:
    app: rhoc
spec:
  selector:
    matchLabels:
      camel.apache.org/integration: "mctr-*"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /q/metrics
      port: http
