apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cos-fleetshard-sync-metrics
  labels:
    app: rhoc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "cos-fleetshard-sync"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /q/metrics
      port: http
